### PR TITLE
add game interface

### PR DESCRIPTION
**Pull request by muhenge**
### Setting up the user game's user interface 

- In this part, we ask for the players one-by-one to select the place of their choice to add a symbol.
- no player is allowed to choose the place consecutively.

### CODE REVIEW

**Review by euqueme — CHANGES_REQUESTED** [review]
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @muhenge and @LOctavio :lollipop: :balloon: 

### Good job so far I see you have the game loop and you have taken into account switching turns for players :video_game:  there is still some behavior to work on :construction: :construction_worker: :construction_worker: you don't have to have it functional at the time but you have to at least put comments on where these behavior is going to be added:

#### Behaviour

* [ ] In this step, not everything must work, the point is to make sure you thought about everything listed below. You may do it only with inline comments. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/logic.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
* [ ] Basic game flow is prepared: ([screenshot hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/logic.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
  * [ ] `[OPTIONAL]` game ask players for their names
  * [ ] `[REQUIRED]` game informs player if selected move is invalid
  * [ ] `[REQUIRED]` game informs player if selected move is a winning move
  * [ ] `[REQUIRED]` game informs player if selected move is a draw move
  * [ ] `[REQUIRED]` game repeats all actions for the next player's move

#### Implementation details

* [ ] Using out-of-nowhere numbers to terminate a loop, is a signal that something is wrong. 

```ruby
  break if(count>9)
  count += 1

```
instead of using a variable that increments and break the loop when it reaches the limit (9 times) use a meaningful variable as the example below.

```ruby
game_on = true

# initial instructions for player

while game_on
  # loop for each move
  
  if winner # and/or draw (the exact condition in this milestone is not important)
    game_on = false
  end
end
```

### That's it, team! :raised_hands: 

### Please :pray: do the changes :technologist: :technologist: and submit back for a code review when you are done :memo: 

Happy Coding! :rocket: 

PROJECT STATUS: REQUESTED CHANGES :vertical_traffic_light:

**Comment by Anna-Myzukina** [comment]
# Hi team! :clap: 
### Good job setting up the project you are missing just one requirement  in Milestone 1 :eyes: 

*  In your project should be `bin` directory with `main.rb` file  from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/)
screenshot
*  `main.rb` is [executable file](https://commandercoriander.net/blog/2013/02/16/making-a-ruby-script-executable/):

* Also I want run this file to Test if this executable file works with next command: 
`bin/main.rb` or `ruby bin/main.rb` and it should displays anything.


### You still need to add as suggested by @euqueme the loop (recommended is `while` but anything else will do).

Using out-of-nowhere numbers to terminate a loop, for example 5.times do ... end is a signal that something is wrong. We recommend the usage of a terminating variable (while game_on) 
### [SUGGESTION] The structure of the game's loop should be as follows:



*The final point of this milestone is to make sure that you thought about all the actions needed to play Tic Tac Toe from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/)


### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*
*Happy coding * <g-emoji class="g-emoji" alias="computer" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f4bb.png">computer</g-emoji>

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi Team     
#### Great Job so far, Just few things to work on. 
### General
### Note: the Basic game flow is :
* [ ]  game tells which player turn it is
* [ ]  game asks player to select from available moves
* [ ]  game informs player if selected move is invalid
* [ ]  game displays board after player move
* [ ]  game informs player if selected move is a winning move
* [ ]  game informs player if selected move is a draw move
* [ ]  game repeats all actions for next player's move


### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Comment by shshamim63** [comment]
## Status :100: Approved
___
Hi @muhenge :wave: ,
Awesome job, I can see all the indications that is needed to guide a user to play this game. This :+1: is from me and best of luck for your next milestone.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain

**Pull request merged**
